USE `loja_de_roupas`;

START TRANSACTION;

DROP TABLE IF EXISTS ITEM_VENDA;

DROP TABLE IF EXISTS PROMOCAO_PRODUTO;

DROP TABLE IF EXISTS VENDA;

DROP TABLE IF EXISTS ESTOQUE;

DROP TABLE IF EXISTS PRODUTO;

DROP TABLE IF EXISTS PROMOCAO;

DROP TABLE IF EXISTS FORNECEDOR;

DROP TABLE IF EXISTS CATEGORIA;

DROP TABLE IF EXISTS FORMA_PAGAMENTO;

DROP TABLE IF EXISTS CLIENTE;

DROP TABLE IF EXISTS FUNCIONARIO;

COMMIT;

START TRANSACTION;

-- Lista de todas as views a serem removidas
DROP VIEW IF EXISTS vw_estoque_baixo;

DROP VIEW IF EXISTS vw_vendas_por_cliente;

DROP VIEW IF EXISTS vw_produtos_mais_vendidos;

DROP VIEW IF EXISTS vw_vendas_por_funcionario;

DROP VIEW IF EXISTS vw_produtos_em_promocao;

DROP VIEW IF EXISTS vw_faturamento_mensal;

DROP VIEW IF EXISTS vw_fornecedores_produtos;

DROP VIEW IF EXISTS vw_metodos_pagamento_utilizados;

DROP VIEW IF EXISTS vw_categorias_faturamento;

DROP VIEW IF EXISTS vw_historico_vendas_detalhado;

COMMIT;
