BEGIN TRANSACTION;

ALTER TABLE Cliente
ADD COLUMN Data_nascimento DATE;

ALTER TABLE Venda
ADD COLUMN Observacoes VARCHAR(255);

ALTER TABLE Venda
ADD COLUMN Codigo_rastreamento VARCHAR(50);

ALTER TABLE Estoque
DROP COLUMN Data_saida;

ALTER TABLE Funcionario
ADD COLUMN Cpf TEXT;

ALTER TABLE Fornecedor ADD COLUMN Cnpj TEXT;

ALTER TABLE Cliente
ADD COLUMN Limite_credito DECIMAL(10, 2) DEFAULT 0;

ALTER TABLE Produto ADD COLUMN Peso DECIMAL(10, 3);

ALTER TABLE Produto ADD COLUMN Ativo BOOLEAN DEFAULT 1;

COMMIT;
