BEGIN TRANSACTION;

DROP TABLE IF EXISTS ITEM_VENDA;
DROP TABLE IF EXISTS PROMOCAO_PRODUTO;
DROP TABLE IF EXISTS VENDA;
DROP TABLE IF EXISTS ESTOQUE;
DROP TABLE IF EXISTS PRODUTO;
DROP TABLE IF EXISTS PROMOCAO;
DROP TABLE IF EXISTS FORNECEDOR;
DROP TABLE IF EXISTS CATEGORIA;
DROP TABLE IF EXISTS FORMA_PAGAMENTO;
DROP TABLE IF EXISTS CLIENTE;
DROP TABLE IF EXISTS FUNCIONARIO;

COMMIT;
