BEGIN TRANSACTION;

-- 1. Tabelas Principais
DROP TABLE IF EXISTS ITEM_VENDA;
DROP TABLE IF EXISTS PROMOCAO_PRODUTO;
DROP TABLE IF EXISTS VENDA;
DROP TABLE IF EXISTS ESTOQUE;
DROP TABLE IF EXISTS PRODUTO;
DROP TABLE IF EXISTS PROMOCAO;
DROP TABLE IF EXISTS FORNECEDOR;
DROP TABLE IF EXISTS CATEGORIA;
DROP TABLE IF EXISTS FORMA_PAGAMENTO;
DROP TABLE IF EXISTS CLIENTE;
DROP TABLE IF EXISTS FUNCIONARIO;

COMMIT;


BEGIN TRANSACTION;

-- 2. Views
DROP VIEW IF EXISTS VW_ESTOQUE_BAIXO;
DROP VIEW IF EXISTS VW_VENDAS_POR_CLIENTE;
DROP VIEW IF EXISTS VW_PRODUTOS_MAIS_VENDIDOS;
DROP VIEW IF EXISTS VW_VENDAS_POR_FUNCIONARIO;
DROP VIEW IF EXISTS VW_PRODUTOS_EM_PROMOCAO;
DROP VIEW IF EXISTS VW_FATURAMENTO_MENSAL;
DROP VIEW IF EXISTS VW_FORNECEDORES_PRODUTOS;
DROP VIEW IF EXISTS VW_METODOS_PAGAMENTO_UTILIZADOS;
DROP VIEW IF EXISTS VW_CATEGORIAS_FATURAMENTO;
DROP VIEW IF EXISTS VW_HISTORICO_VENDAS_DETALHADO;

COMMIT;
